Homepage
Sulemana24/PulseBit- pull request #1
Opened 2024-10-21 12:24 UTC by Sulemana24

Made changes to footer text

2024-10-21 19:36 UTC, gogurlbaby commented
### Required Changes ♻️

Hi @Sulemana24.

Good job so far!
There are some issues that you still need to work on to go to the next task but you are almost there!

![159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff](https://github.com/user-attachments/assets/b3fc9a9c-eae4-4edf-8e18-b748cc6ae8c2)

### Highlights

✔️ Correct File Structure

### Required

- [ ] _Check the comments under the review._

### Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@gogurlbaby ] in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

2024-10-21 20:28 UTC, gogurlbaby commented
### Apply These Changes Effectively

### Well done!! Nice Website

### Comments
1. Use comments to describe your work or differentiate sections. 
Eg.
 `<!-- Navbar Section-->`
 `<!-- Hero Section-->`

**Remove the comments you do not need in your work. 
Not a good practice to send multiple comments of a section for review.**

### NavBar Section

2. Nice Navbar. I love how you used the same container for both desktop and mobile nav-items.

- The hover on the **home nav-item** clashes with the white background color of the section on the left. 

- Either give the nav-items more margin on the left or change the hover color for home.

**Hero Section**
 
3. The hero section looks excellent but align the **Play video** text and icon.

### Content Section

**Latest Articles Section**

4. Excellent 💯 

- Add enough padding to the buttons on the section.

- Align the search input and search button.

- No need to use a placeholder called search again with search  as text too on the button. Rephrase it rather. Eg. Search for more articles. Or you can maintain the search placeholder and use a search icon instead of the button.


**Testimonial Section (What Our Visitors Say Section)**

5. It looks good but I suggest you make the section span. 

- Then you can have 2 testimonials cards each for desktop and one card for mobile.

- Consider the content. Read it well and make the necessary corrections, where appropriate.

### Footer Section

6. The footer section looks good but use margin bottom to space out the items on the section. Give them enough breathing space.


### Mobile Section

- Almost all the sections looks good for mobile and tablet.

- The hero section is shifted to the left and the latest articles section is shifted to the right. **Fix them**

### Styles Section

Very good use of the css. Use of variables, class selectors, pesudo-classes and pseudo-elements are all on point. 

**KEEP IT UP** 👍

2024-10-21 20:29 UTC, gogurlbaby requested changes
Kindly work on the requested changes ASAP so we move to the next pages.

2024-10-23 17:26 UTC, Sulemana24 commented
Changes are made pls. Kindly check them out @gogurlbaby

2024-10-24 21:59 UTC, gogurlbaby commented on home.html
> +        <!--Navbar Section-->
Good

2024-10-24 21:59 UTC, gogurlbaby commented on home.html
>  </head>
Add a favicon to your title.

2024-10-24 22:00 UTC, gogurlbaby commented on home.html
>                  <h1>The Future of Artificial Intelligence.</h1>
Reduce the font-size of the title for mobile.

2024-10-24 22:10 UTC, gogurlbaby commented on home.html
>              <div class="nav-logo">
Try using a different color for the hover effect for the nav-items. It should contrast the background-color of contact-us button.

Do not use same class name for id. How do we tell the difference?

2024-10-24 22:12 UTC, gogurlbaby commented on home.html
> +        <!--Top Stories Section-->
The background-color of latest articles is visible at the extreme right section of the top stories section. Fix it.

2024-10-24 22:14 UTC, gogurlbaby commented on home.html
> +        <div class="testimonial-card">
Very good on applying the changes for this. However, add enough padding for top and bottom for the cards. Overall they look very good.

2024-10-24 22:15 UTC, gogurlbaby commented on home.html
> +                    <input type="text" id="input" placeholder="Search our blog...">
Perfect!

2024-10-24 22:16 UTC, gogurlbaby commented on home.html
>      <footer class="footer" id="news">
Input for footer section is too big. Fix it.

2024-10-24 22:17 UTC, gogurlbaby commented on home.html
> +                    <a href="https://www.youtube.com/watch?v=dv9q7Ema40k" target="_blank">Play video <span><i class="ri-play-circle-fill"></i></span></a>
Looks good but add enough gap between the text and icon.

2024-10-24 22:19 UTC, gogurlbaby commented on home.html
> +            Copyright <i class="ri-copyright-line"></i> 2024 Bindawdi Enterprise.
It seems the green background-color is over powering the white color text. Try tweaking it a bit to be very visible.

2024-10-24 22:22 UTC, gogurlbaby commented on home.html
> +    <h2 class="testi-head">What Our Visitors Say?</h2>
Reduce font-size for mobile.

2024-10-24 22:28 UTC, gogurlbaby commented
### Responsiveness

- _A TIP: Start styling your page for mobile first and then use media queries to make it responsive for desktop and tablet._  

**That way you make things easy for yourself.**

- _So inspect your page and start styling for mobile first_ 


### **SUBMISSION: TUESDAY**

**Immediately reach out if you are not clear about something**

**All the best!!**

2024-10-24 22:31 UTC, gogurlbaby requested changes
Create a new branch called fix-homepage and push your new changes there.

First create the branch and start working in that.

2024-10-29 21:00 UTC, Sulemana24 commented
New branch has been created. And all changes has been made, pls check on it @gogurlbaby

2024-10-30 23:17 UTC, merged